"""add impressions and clicks

Revision ID: b64f89d9fbbb
Revises: f70f8f0c9d9f
Create Date: 2026-01-07 12:40:24.768556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b64f89d9fbbb'
down_revision = 'f70f8f0c9d9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_request_id', sa.Integer(), nullable=False),
    sa.Column('price_micro', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ad_request_id'], ['ad_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('click', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_click_ad_request_id'), ['ad_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_click_created_at'), ['created_at'], unique=False)

    op.create_table('impression',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_request_id', sa.Integer(), nullable=False),
    sa.Column('price_micro', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ad_request_id'], ['ad_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('impression', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_impression_ad_request_id'), ['ad_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_impression_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('impression', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_impression_created_at'))
        batch_op.drop_index(batch_op.f('ix_impression_ad_request_id'))

    op.drop_table('impression')
    with op.batch_alter_table('click', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_click_created_at'))
        batch_op.drop_index(batch_op.f('ix_click_ad_request_id'))

    op.drop_table('click')
    # ### end Alembic commands ###
