"""add ad request

Revision ID: f70f8f0c9d9f
Revises: 
Create Date: 2026-01-07 12:28:16.520282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f70f8f0c9d9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_advertiser', sa.Boolean(), nullable=False),
    sa.Column('is_publisher', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('bid_cpm_micro', sa.BigInteger(), nullable=True),
    sa.Column('bid_cpc_micro', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_user_id'), ['user_id'], unique=False)

    op.create_table('ledger_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('amount_micro', sa.BigInteger(), nullable=False),
    sa.Column('ref_type', sa.String(length=50), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entry_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entry_entry_type'), ['entry_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entry_user_id'), ['user_id'], unique=False)

    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_user_id'), ['user_id'], unique=False)

    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance_micro', sa.BigInteger(), nullable=False),
    sa.Column('reserved_micro', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('balance_micro >= 0', name='check_balance_non_negative'),
    sa.CheckConstraint('reserved_micro >= 0', name='check_reserved_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_user_id'), ['user_id'], unique=True)

    op.create_table('ad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('landing_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ad_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_status'), ['status'], unique=False)

    op.create_table('slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('floor_cpm_micro', sa.BigInteger(), nullable=True),
    sa.Column('floor_cpc_micro', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('height > 0', name='check_height_positive'),
    sa.CheckConstraint('width > 0', name='check_width_positive'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slot_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_slot_status'), ['status'], unique=False)

    op.create_table('ad_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('price_cpm_micro', sa.BigInteger(), nullable=False),
    sa.Column('price_cpc_micro', sa.BigInteger(), nullable=False),
    sa.Column('reserved_impression_micro', sa.BigInteger(), nullable=False),
    sa.Column('reserved_click_micro', sa.BigInteger(), nullable=False),
    sa.Column('reserved_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('impression_tracked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('click_tracked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ad.id'], ),
    sa.ForeignKeyConstraint(['advertiser_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['slot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ad_request_ad_id'), ['ad_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_request_advertiser_id'), ['advertiser_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_request_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_request_publisher_id'), ['publisher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_request_request_id'), ['request_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_ad_request_reserved_until'), ['reserved_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_request_slot_id'), ['slot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_request_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_request_status'))
        batch_op.drop_index(batch_op.f('ix_ad_request_slot_id'))
        batch_op.drop_index(batch_op.f('ix_ad_request_reserved_until'))
        batch_op.drop_index(batch_op.f('ix_ad_request_request_id'))
        batch_op.drop_index(batch_op.f('ix_ad_request_publisher_id'))
        batch_op.drop_index(batch_op.f('ix_ad_request_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_ad_request_advertiser_id'))
        batch_op.drop_index(batch_op.f('ix_ad_request_ad_id'))

    op.drop_table('ad_request')
    with op.batch_alter_table('slot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slot_status'))
        batch_op.drop_index(batch_op.f('ix_slot_site_id'))

    op.drop_table('slot')
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_status'))
        batch_op.drop_index(batch_op.f('ix_ad_campaign_id'))

    op.drop_table('ad')
    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_user_id'))

    op.drop_table('wallet')
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_user_id'))

    op.drop_table('site')
    with op.batch_alter_table('ledger_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entry_user_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entry_entry_type'))
        batch_op.drop_index(batch_op.f('ix_ledger_entry_created_at'))

    op.drop_table('ledger_entry')
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_user_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_status'))

    op.drop_table('campaign')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
